Issue #155552 task:Create a resource in tjreports API plugin to get the fields compatible with google DS for a report
techjoomla/plg_api_tjreports pull request #6
Opened 2020-01-03 06:54 UTC by twsvaishali

…he fields compatible with google DS for a report

2020-01-04 09:35 UTC, coolbung commented on src/reports/gsfields.php
> +		$formData   = $jinput->post;
Are you trying to use POST data in the get function ?

2020-01-06 13:35 UTC, coolbung commented on src/reports/gdsfields.php
> +		$jinput     = $app->input;
Is this variable used ?

2020-01-06 13:37 UTC, coolbung commented on src/reports/gdsfields.php
> +		if (!method_exists($reportPlugin, 'getGoogleDsFields'))
Do you want to change the method name to `getGDSFields` ?

2020-01-07 12:02 UTC, thite-amol requested changes

2020-01-07 12:02 UTC, thite-amol commented on src/reports/gdsfields.php
> + * @subpackage   com_api
@twsvaishali Change subpackage `com_api` to `API`

2020-01-07 12:02 UTC, thite-amol commented on src/reports/gdsfields.php
> + * @copyright    Copyright (C) 2009 - 2018 Techjoomla. All rights reserved.
@twsvaishali Change the copyright year

2020-01-07 12:02 UTC, thite-amol commented on src/reports/gdsfields.php
> + * @since  1.1.0
@twsvaishali Use constant

2020-01-07 12:02 UTC, thite-amol commented on src/reports/gdsfields.php
> +		$app        = JFactory::getApplication();
@twsvaishali Use the namespaces for all deprecated classes

2020-01-07 12:02 UTC, thite-amol commented on src/reports/gdsfields.php
> +		$fields = $reportPlugin->getGDSFields();
@twsvaishali Avoid this useless variable

2020-01-07 12:02 UTC, thite-amol commented on src/reports/gdsfields.php
> +	 *
@twsvaishali Update the function comments

2020-01-07 17:38 UTC, coolbung requested changes
The custom attribute method needs to be updated

2020-01-07 17:38 UTC, coolbung commented on src/reports/report.php
> +		$this->plugin->customAttributes->set("total", $reportPlugin->getTotal());
Don't think this is a good idea. We can't expect developers to know this internal attribute named `customAttributes`

Needs to be `$this->plugin->setCustomAttribute($key, $value)`

2020-01-08 10:09 UTC, merged